version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '6006:6006'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
