name: Run tests and merge before publish package
on:
  push:
    branches:
      - 'staging'

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup packages
        run: npm install

      - name: Merge staging
        uses: devmasx/merge-branch@master
        message: 'merge staging'
        with:
          type: now
          target_branch: releases
          github_token: ${{ github.token }}
