name: Run tests and merge before publish package
on:
  push:
    branches:
      - "staging"

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup packages
        run: npm ci

      - name: Run all tests
        run: npm run test

      - name: Merge staging
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: releases
          github_token: ${{ github.token }}
